### PR TITLE
Remove unused include

### PR DESCRIPTION
**Pull request by sebastian-s-beckmann**
### Description

Removes an unneeded import.

### Motivation and Context

025ab52 removed QMacCocoaViewContainer, but not the `#include`. However, the that isn't needed anymore.

### How Has This Been Tested?

Still compiles on macOS (12.0.1).

### Types of changes

- Code cleanup (non-breaking change which makes code smaller or more readable)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by notr1ch** [comment]
Might be good to fix the #ifs to #if defined() while we're at it.

**Comment by sebastian-s-beckmann** [comment]
@notr1ch that would be `defined(_WIN32)` or `ifdef _WIN32` then, right?
(I don't have a windows build environment so I'm a little hesitant to touch this)

**Comment by notr1ch** [comment]
Yeah, `#if` tests a constant value, `#if defined(xx)` tests if xx is defined. Given many build environments simply pass `-DVARIABLE` and not `-DVARIABLE=1`, testing with `#if` can produce wrong results.

And yes it should also be `_WIN32` not `WIN32`.

**Comment by WizardCM** [comment]
Verified this builds on Windows and Linux.

**Pull request merged**
