### PR TITLE
obs-vst: Add ability to set custom path

### PR DESCRIPTION
**Pull request by cg2121**
### Description
Adds ability for users to select custom path for VSTs.

Capture

### Motivation and Context
https://ideas.obsproject.com/posts/939/customvst-search-path

### How Has This Been Tested?
Added VSTs to folder, then selected the folder and made sure the VST list was correct.

### Types of changes
- New feature (non-breaking change which adds functionality)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by Subby** [comment]
Any update on this? Would be a great feature

**Comment by armak** [comment]
This feature would be sorely needed, please merge.

**Comment by mrmbp** [comment]
This will be a great feature when it's ready. 

I'm wondering if it's possible to edit the config files to add a path manually, in Win10.

**Comment by KevinNorth** [comment]
Pleaese merge this.

**Comment by KevinNorth** [comment]
Please merge this. I'm into music production and have dozens of VSTs I'd like to use, but I'm particular about how I install them. Not being able to easily use them in OBS only because I can't set my VST directory is a relatively small thing, but it doesn't feel good either :P

**Comment by qcksilver** [comment]
I came here from https://obsproject.com/forum/threads/custom-vst-path.129320/ I'm also in music / live event production and just wondering if anyone knows a rough ETA on when this feature will be added? 

Big thanks to everyone who has been working on this! I'm really looking forward to it, and I'm crossing my fingers development has stopped on this 🤞 😟

**Comment by nxiromeritis** [comment]
Also really interested in this, as I try to keep VSTs organized in a particular folder. In my opinion this is a basic and must-have feature for the tool and any kind of tool. Although I see it hasn't been integrated yet. Any chance this will be approved/merged in the near future? Thank you for implementing this feature!

**Comment by Inversil** [comment]
please merge this!!

**Comment by legithubuser** [comment]
Please get it out I am on the brink of crying cause it's not here, I really need it!

**Comment by WizardCM** [comment]
Rather than having this as a setting per-filter (which could get messy), we think it'd be better to have a new entry in Tools that allows the user to manage as many custom paths as the user wants, plus (eventually) the ability to hide/show VSTs from the list.

**Pull request closed without merging**
