### PR TITLE
obs-vst: Fix crash by checking hash before applying "chunk_data"

### PR DESCRIPTION
**Pull request by walker-WSH**
### Description

Before applying chunk-data, we should check if data is for this VST plugin.
Some VST plugin will crash at effSetChunk if chunk-data is not for it.
Besides, it is meaningless to apply chunk-data to a mismatched VST plugin.

For example:

It can also be reproduced with:
readelay-standalone.dll
BL-Denoiser.dll
spire-1.5.dll

### Motivation and Context

Fix crash

### How Has This Been Tested?

switch selected VST and reboot OBS

### Types of changes
Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by WizardCM** [comment]
How would a user fall into this error case?

**Comment by walker-WSH** [comment]
> How would a user fall into this error case?

How to reproduce this crash ?
1. add VST filter for audio source, select any available VST plugin (eg: named "VST-1");
2. exit OBS, then chunk-data of "VST-1" will be saved;
3. run OBS, switch VST plugin from VST-1 to "BC Triple EQ 4 VST";
    chunk-data of "VST-1" will be applied to "BC Triple EQ", then crash!

**Comment by WizardCM** [comment]
Could you list a couple of free VST plugins that this issue can be reproduced with?

**Comment by walker-WSH** [comment]
> Could you list a couple of free VST plugins that this issue can be reproduced with?

I have attached a image for free VST plugin, you can use it to reproduce.

**Comment by walker-WSH** [comment]
@WizardCM    

this VST plugin can also be used to reproduce:
**readelay-standalone.dll
BL-Denoiser.dll
spire-1.5.dll**

**Comment by WizardCM** [comment]
Unfortunately I am unable to reproduce this crash on current master.

**Comment by walker-WSH** [comment]
> Unfortunately I am unable to reproduce this crash on current master.

That is strange. I can reproduce it every time with the given Plugins.
I tried apply chunk-data of different Plugin to the given Plugins, crash still happen.

Even you can't reproduce it, we should not apply chunk-data of plugin A to plugin B. 
So I think this commit is necessary.

**Comment by WizardCM** [comment]
I agree.

**Pull request merged**
